
train_data_folder = 'data'
vehicles_train_data_folder = train_data_folder + '/vehicles'
non_vehicles_train_data_folder = train_data_folder + '/non-vehicles'
vehicles_train_data_p = train_data_folder + '/vehicles.p'
non_vehicles_train_data_p = train_data_folder + '/non_vehicles.p'
vehicles_histograms_p = train_data_folder + '/vehicles_hist.p'
non_vehicles_histograms_p = train_data_folder + '/non_vehicles_hist.p'
vehicles_spatial_bins_p = train_data_folder + '/vehicles_sbin.p'
non_vehicles_spatial_bins_p = train_data_folder + '/non_vehicles_sbin.p'
